[Main]
RealAppId=1766060
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[Hashes]
0=0f9580f636d4abfb97fa5f738317a75cb73d738db682c1d161fc16be3ce2f07b09efd5220213e8c40b80dc7cf298cf549b8dec672c1746e823093cb21579ae5a
