[Main]
RealAppId=2095420
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[DLC]
4140550=SteamDB Unknown App 4140550
4028530=Bus Bound - Bus Pass
3796400=Bus Bound - Retro Bus Pack
3796390=Bus Bound - Modern Bus Pack

[Hashes]
0=1567480fa90a719c60160b28e87f521b529405cb7e6f631e163ec29dd241f803d0b490b46409fcd3cb7f4b851a4bb287ca61e2aed3a353b94cad1e279511959f
