[Main]
RealAppId=2625420
FakeAppId=480
#Language=english
BuildId=18447039
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=6db8c3201342adc6c84354be059c3219079bc24c840bc1761807264ae7c302415a993d8baccf0a087c64345f2046380073cb318927c562062fc028fc6641caa1
