[Main]
RealAppId=648800
FakeAppId=480
#Language=english
BuildId=20653906
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=fb28a100ed793c082be9c6db762ee82d46069bfefcbd010f9edeaf358c7230a1a61f464c7917e4d68c898ef53176ab569551bd30608786542afc5a0a295eed81
