[Main]
RealAppId=3333740
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=05b5e3d5a46bff80457ccac853a5d3e10cd0941533113af5aa36e4ca9df123268b792e4b0aa3edc863304eadf8f4bc3c44a3daed68a8109965c4b2247e744b54
