-- 1342490's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Daemon X Machina: Titanic Scion
-- Generated: 2025-09-05 12:33:27
-- Total Depots: 4
-- Total DLCs: 7 (1 excluded)
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(1342490, 1, "23dd752c2a079cb0e28aacc6cc7286c228f93bf412691cfa6fa8d112d56ed876") -- Daemon X Machina: Titanic Scion
-- MAIN APP DEPOTS
addappid(1342491, 1, "c6540bdf8c309fb168778b2fbe5a1f6fd5802ca36eb9ac410f78e2bce2d4b57f") -- Depot 1342491
setManifestid(1342491, "5013354445104201572", 48609055545)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITH DEDICATED DEPOTS
-- Daemon X Machina Titanic Scion - Art Book (AppID: 3779150)
addappid(3779150)
addappid(3779150, 1, "7f846f37bcfb01890a3bf2c2a91724c2342f38d3085da2354f573476227b405b") -- Daemon X Machina Titanic Scion - Art Book - Depot 3779150
setManifestid(3779150, "951698471833675111", 520153184)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3766440) -- Daemon X Machina Titanic Scion - Special Equipment Set
addappid(3766450) -- Daemon X Machina Titanic Scion - Bonus Item Set
addappid(3766550) -- Daemon X Machina Titanic Scion - Special SFX Weapon Set
addappid(3766560) -- Daemon X Machina Titanic Scion - Arsenal Skin Set
addappid(3974080) -- Daemon X Machina Titanic Scion - Free Hairstyles
addappid(3974090) -- Daemon X Machina Titanic Scion - Free Emotes
-- EXCLUDED DLCS:
-- UNRELEASED DLCS (COMMENTED OUT)
-- addappid(3787730) -- DLC 3787730 (unreleased)