-- 1346840's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Dead Reset
-- Generated: 2025-09-15 21:46:14
-- Total Depots: 2
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1346840) -- Dead Reset
-- MAIN APP DEPOTS
addappid(1346841, 1, "97c6131497053c1bb5d67ba18ab299d620ed9102c349d33a39a88f631ffbea41") -- Depot 1346841
setManifestid(1346841, "4785986818608701145", 14884984455)
addappid(1346842, 1, "639e6998b8fd3c6504cc09f16dc96c068665e905632e4045daa48aae2f01c32c") -- Depot 1346842
setManifestid(1346842, "3363920022168361767", 238145799)