-- 1702590's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Casa Caballero
-- Generated: 2025-08-27 14:32:34
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1702590) -- Casa Caballero
-- MAIN APP DEPOTS
addappid(1702591, 1, "f216a584f3b1d36d001e469ff1a530777cd8d23bab562dcc13d2723e128a9be8") -- Depot 1702591
setManifestid(1702591, "4885967082318325801", 4462445256)