-- 2133760's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Tiny Bookshop
-- Generated: 2025-08-09 11:06:27
-- Total Depots: 3
-- Total DLCs: 0 (1 excluded)

-- MAIN APPLICATION
addappid(2133760) -- Tiny Bookshop
-- MAIN APP DEPOTS
addappid(2133762, 1, "d52e06a500706a15e7821f6a7c3e30d1a2bce0ea65b784d6a387cdadef756a78") -- Depot 2133762
addappid(2133763, 1, "788e7476ac625a7a50f7add2445dc120f1524ee6dc56b8f14edec6a2f954474a") -- Depot 2133763
addappid(2133764, 1, "1ebff4822d7fe419fe87324ea8a05d3dc5b985322407afcd0ad15c10f340eba7") -- Depot 2133764
-- EXCLUDED DLCS:
-- DLCS EXCLUDED (MISSING DEPOT KEYS)
-- Tiny Bookshop Digital Artbook (AppID: 3933690) - missing depot keys
-- addappid(3933690)