-- 2589500's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Whisper of the House
-- Generated: 2025-09-03 13:05:06
-- Total Depots: 2
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(2589500, 1, "5163fe41419ecfe3e90105d7df21b63bea613635c470bc40684a61343139d02a") -- Whisper of the House
-- MAIN APP DEPOTS
addappid(2589501, 1, "6f51226f61dd888511279cdc32b68f2eafddb79f8d92998ffcac30e6dae73021") -- Depot 2589501
setManifestid(2589501, "6747169787921929843", 1684541980)
addappid(2589502, 1, "4b0d0eb017d111efc9280dba6335288de7d0c691d506d8ab30559a254745f0c2") -- Depot 2589502
setManifestid(2589502, "6052199061058786765", 1270030977)