-- 2949320's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Ratatan
-- Generated: 2025-09-19 14:55:00
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(2949320) -- Ratatan
-- MAIN APP DEPOTS
addappid(2949321, 1, "3b33d27a923706d4e15053028684f05880816915c68004b0e4c9f341b711e664") -- Depot 2949321
setManifestid(2949321, "1560397371653734735", 1787954445)