-- 3115220's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Town To City
-- Generated: 2025-09-18 16:47:25
-- Total Depots: 3
-- Total DLCs: 0 (1 excluded)
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(3115220) -- Town To City
-- MAIN APP DEPOTS
addappid(3115221, 1, "2bee0d6f4424d4ab2e390fe00b111e2c779f83a34f8a9fd16984e6edba09f8be") -- Depot 3115221
setManifestid(3115221, "5092211180798939435", 2106699887)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- EXCLUDED DLCS:
-- DLCS EXCLUDED (MISSING DEPOT KEYS)
-- Town to City Digital Artbook (AppID: 3873380) - missing depot keys
-- addappid(3873380)