-- 3201010's Lua and Manifest Generated by Morrenus
-- Starlight Re:Volver
-- Generated: 2025-09-26 00:24:02
-- Total Depots: 2
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3201010) -- Starlight Re:Volver
-- MAIN APP DEPOTS
addappid(3201011, 1, "d1d08539c276061ca3555b2aab801c92cf7791cc7dd48861a8d92a1a5217b0cb") -- Depot 3201011
setManifestid(3201011, "2288008761986005850", 2622889982)
addappid(3201012, 1, "751e4bb432fc4bc3ad95b25303eaaeab8c958a2a7f5743d83cd1122a17fb45ce") -- Depot 3201012
setManifestid(3201012, "7657118855442245741", 64417894)