-- 3354750's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- skate.
-- Generated: 2025-09-17 02:48:15
-- Total Depots: 1
-- Total DLCs: 4

-- MAIN APPLICATION
addappid(3354750) -- skate.
-- MAIN APP DEPOTS
addappid(3354751, 1, "12f0eab99e98b8912cb7e80d06eb068409135cc2968fc071880ac3f5850e1722") -- Depot 3354751
setManifestid(3354751, "876401416436541781", 8784372169)
-- DLCS WITHOUT DEDICATED DEPOTS
addappid(3354800) -- skate. Meatman Cosmetics and 3,100 San Van Bucks
addappid(3354810) -- skate. - skate Tees and Vans Founders Shoes
addappid(3354820) -- skate. - Mocap Cosmetics and 2,800 San Van Bucks
addappid(3494010) -- skate. - Founding Founders Cosmetics and S1 skate.Pass