-- 3405340's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Megabonk
-- Generated: 2025-09-19 01:32:22
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3405340) -- Megabonk
-- MAIN APP DEPOTS
addappid(3405342, 1, "0fbab2971279bba685debbfa503e2da7e014fb5066cec822fcda80f9465e304e") -- Depot 3405342
setManifestid(3405342, "4301663095342179654", 433669235)