-- 3467040's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Bookshop Simulator
-- Generated: 2025-09-17 02:48:25
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3467040) -- Bookshop Simulator
-- MAIN APP DEPOTS
addappid(3467041, 1, "7416c54d61cf32054ec624e2d1c4e3a825c272e5e79cd38461665165df5e7e61") -- Depot 3467041
setManifestid(3467041, "4154886056546537690", 7012277098)