-- 3527290's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- PEAK
-- Generated: 2025-08-02 04:33:25
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3527290, 1, "499eb049b24a30730d5926e9cf72bfa9237d1a7f6de06e94a05e9c2c01348478") -- PEAK
-- MAIN APP DEPOTS
addappid(3527291, 1, "f55585bb6a00ba332421256f80ba05e27afc38fec6170b9a763138244c506f05") -- Depot 3527291
setManifestid(3527291, "4678309781913594895", 5737182183)