-- 3869680's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Silent Still 2
-- Generated: 2025-08-21 17:44:32
-- Total Depots: 1
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(3869680) -- Silent Still 2
-- MAIN APP DEPOTS
addappid(3869681, 1, "9ddce3458ea9f0dab580448841013dfb9d668d0424934a492bed2f8abbbafd86") -- Depot 3869681
setManifestid(3869681, "4130377789863100814", 4261318082)