[Main]
RealAppId=1910150
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=c492b67bb86c6801885e5f49d4460cd861a06d29b9f13c01964b5bc507f6aa2976e055eb383806fc2ade7e00b39b0ce8c55d776a6633c8a113399e1f395480f5
