[Main]
RealAppId=892970
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=63451aa2ba5fe7e2efb0290fb74d3dfde16feef47189bc36b10884c851c220a6809518784fcfc2f9c52c0fb28c2f138f568bc8a7b7b231062686d808842c8fe7
