[Main]
RealAppId=2070270
FakeAppId=480
#Language=english
BuildId=21059475
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[DLC]
4164290=Cloudheim - Supporter Pack

[Hashes]
0=1f8f919f9b985f939e751999decc45bb50d017c00f220ec3382efa4150848bc55c1a07684af322069b4fe120d0f5a9b15dacbe0223ccda2d81d9882a692b62c2
