[Main]
RealAppId=3949040
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=fb72f20bf7c69dc6260e16dac53b3df8a7ffb34d3f33c8aa32d1202ce609b0308c0bb2ec8f8fde1bc13a455665c39bc0445b7ca02a3306665d85c8313fcbbf60
