[Main]
RealAppId=3716600
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=a763e4f364c0bb8312b1e0802cb50f95afe7bbadb65812b27dc844eff732bedd89a04c2ad7832e70624f87959ac7c7f60a1aa6368aa9bec3e3d08d9b4bc07af1
