[Main]
RealAppId=1609370
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[DLC]
3755710=Founders Limited Edition Pack

[Hashes]
0=384edc469a221c2ccbb62b7f1b92c7f5d650f0b514f664098720aff242d6f7652b79a5046b234ded5a403976a7de6d655bd3477767b2ce8380a0d9a36d3eea12
