[Main]
RealAppId=1062520
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=633c73c6b50521a2d716626b5ef3d0596e9ac4e32fddb8f56308ff253214f5338d9a6f92dbf8f5db55fd44394e1e7e419c3859f89c02f80c4f6181fd31631867