[Main]
RealAppId=2879840
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=fef9bad45e0569867394447e8c263f87a8b00d304fb60ef0e51717939f698757e1fd4d59d201615f289441cbbfb933dcfed2bd8c75cbc564c4c7cd6ccd659937
