[Main]
RealAppId=3004140
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=4f280c258d0de4e2009ffde7e84e9a29eacd1960f7574134489266cc4bf5c08dc2d9513739b95a0a708fdfd8d842c0b3ed7f59d7770c8748ad20cbced5565f96
