[Main]
RealAppId=3008130
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[DLC]
3707710=Dying Light: The Beast Standard to Deluxe Upgrade
3707650=Dying Light: The Beast - Castor Woods Prepper Bundle
3707640=Dying Light: The Beast - Wallpapers
3707630=Dying Light: The Beast - Map Guide
3707620=Dying Light: The Beast - Soundtrack
3592040=Dying Light: The Beast - Hero Of Harran Bundle

[EOSAuthWrapper]
DeviceIdAuth=true

[Hashes]
0=98275472281cafef96ca957c3fdb0d19ad3c7c25798f9e79e3de400fec6894ed725f9e19105bc581da25ed0891e20fe38f1ec93f8f2dd1cbad6b1608d244de39
1=d73fdbb253480785bab96797b787d0793bb7f4b1ab45e81193b922db56700974f45036d073c847ce73393a626c70ad3ddb0ac86e87f5851b037d1aa6b66b9525
