[Main]
RealAppId=3008130
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[DLC]
4537200=Dying Light: The Beast Restored Land Definitive Upgrade
4355480=Dying Light: The Beast - Discharge Weapon Pack
4355470=Dying Light: The Beast - Fire Lotus Weapon Pack
4355460=Dying Light: The Beast - Hunter Essentials
4355450=Dying Light: The Beast - Action Hero Essentials
3707710=Dying Light: The Beast Standard to Deluxe Upgrade
3707650=Dying Light: The Beast - Castor Woods Prepper Bundle
3707640=Dying Light: The Beast - Wallpapers
3707630=Dying Light: The Beast - Map Guide
3707620=Dying Light: The Beast - Soundtrack
3592040=Dying Light: The Beast - Hero Of Harran Bundle

[EOSAuthWrapper]
DeviceIdAuth=true

[Hashes]
0=2f841835ab1698ad4ab9005775aae69dca19446f23987a0c0a816e6cd553dfa0a726213a20409e77197c91673282d0f56aad9674ca874171fcc6c8df49318a49
1=bc778408adb482b1c585db7b7ded9debf8004ca5bf3fd8eeb171b89ca1d5734e1f204e2a587b68b2bb523df5a55a9c6da0d61fe031eeb669ad4887293a3395f9
