[Main]
RealAppId=1857950
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=1a012b2e7e2f3e209015caaf6f05cbd70803e2ccfc0e586683bc8c63b15a203ed846ad96164ee97a927c17e995d68ae9f143dcb318dcf1626718a7e4b5cecdb8
