[Main]
RealAppId=3278310
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=false
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=c0010fdeefc73e2b8629169d1423a56bd55c6b1363893d538654f900eb3e3a41fabab48edc0cb599dc49c36f8d84fd5b71cc8d5e27acd7b6817eac78b57908a3
