[Main]
RealAppId=1062520
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=a0d80dca017c18fa313e3d7424272bb381df2f0e2933a4cbbb8e1af363b6e026efb87f2b2a3b973fc24bcd77807ed8b885638ecb47e7397e220d0e830490440f