[Main]
RealAppId=3834090
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=a57289437b38af7e2189369d53c6c4296e3cd9a9dbcc565d5eb6386e3ebde91a4a4fc9d4fc7bd31111c94b0c0a6cbfa2b684a7cc6ba08a697af05175876342ad
