[Main]
RealAppId=2827200
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=e36fdda8376927d118bac9fa2668b5aa958c86d6ef2e59c2908abbc5755a2301d7f916deb52605c2608f974fff5c7552eff4bb1f976f7f86ae58a8ca5b58df6e
