[Main]
RealAppId=3265230
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=7785b86d6aab1db8a91eba8d4e6d80663df697efa74762997d4ac4a4f1278409f9018bc4be111e4c8c536b3e89dafb2e9848feed6a5b88d846effffcfa5c5e9c
