[Main]
RealAppId=2956680
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=e89d28d84b598c2e7cc7f17a599d8bb854f61720ce763205cda3ecf831786f46e2ed98fe2cad60133ccbe8f3cd76958584b29c972aa6315f9720fc673602ec9e
