[Main]
RealAppId=1119730
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
BasicProfile=true
FriendsList=true
Presence=true
Country=true

[DLC]
3255980=Ranch Simulator: Southwest Ranch & Farm Expansion Pack

[Hashes]
0=2d6fb5f5b70731a0fcf160f691145319fa6994345f5e4d022f67b5caf7bb38f5fcfa5c0f506620051123cbb3e4f7c8d24b977682b474fe2c61c940e659b4f10e
