[Main]
RealAppId=2625420
FakeAppId=480
#Language=english
BuildId=22587174
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[Hashes]
0=4bfa4bb5d733e7ff16fbffa0196a38f115de0f913784d5667eb4f1daba93a8ad2c7829619f8e12d350fb38736a2d6d2ea48764f7841bcdee2ca5db8dea5d0e1a
