[Main]
RealAppId=1631270
FakeAppId=480
#Language=english
BuildId=0
InstallDir=
UnlockAllDLC=false

[Misc]
ExtraProtection=false
PhotonIntegration=false
EmulateTicket=false

[Interfaces]
Apps=true
User=true
Utils=true
Storage=true
UserStats=true
Friends=true
UGC=true
Inventory=true
AppTicket=true

[EOSAuthWrapper]
DeviceIdAuth=true

[DLC]
4167250=StarRupture - Supporter Pack

[Hashes]
0=2713024ccecea026ca4641ac3f6e6617170009807cf97cef874e78bc791be017a17304f0c8959198746768e286eb51ffa6d7c55de462efe3e5f2d7b45667c33b
